import { catalog } from "./catalog";

// Only interaction state crosses previews; services, callbacks and layout stay local.
export const syncBindings: Record<string, readonly string[]> = {
  "knx-tabs-subpage-data": ["showFilters"],
  "knx-list-filter": [
    "selectedOptions",
    "expanded",
    "filterQuery",
    "pinSelectedItems",
    "sortCriterion",
    "sortDirection",
  ],
  "knx-sort-menu": ["sortCriterion", "sortDirection"],
  "knx-sort-menu-item": ["active", "direction"],
  "knx-time-delta-filter": ["expanded", "deltaBefore", "deltaAfter"],
  "knx-time-range-filter": ["expanded", "startMs", "endMs"],
  "knx-sticky-expansion-panel": ["expanded"],
  "knx-separator": ["height"],
  "knx-table-cell-filterable": ["filterActive"],
  "knx-selector-row": ["value", "_enabled", "_haSelectorValue"],
  "knx-sync-state-selector-row": ["value", "_minutes"],
  "knx-dpt-option-selector": ["value"],
  "knx-dpt-dialog-selector": ["value"],
  "knx-single-address-selector": ["value"],
  "knx-group-address-selector": ["config", "_showEmptyPassiveField"],
  "knx-payload-selector": [
    "value",
    "_mode",
    "_typedValue",
    "_rawPayload",
    "_rawLength",
    "_linkedDpt",
    "_rawPayloadBase",
  ],
  "knx-select-options-list": ["value", "_linkedDpt", "_payloadLength"],
  "knx-configure-entity": ["config"],
  "knx-form": ["config", "_selectedGroupSelectOptions"],
  "knx-device-picker": ["value", "_deviceId", "_opened"],
  "knx-project-device-tree": ["_selectedDevice"],
  "knx-project-tree-view": ["_selectableRanges"],
  "knx-project-devices-view": [
    "searchText",
    "filterDpt",
    "filterLocation",
    "filterLine",
    "_expanded",
    "_collapsedChannels",
    "_manuallyCollapsed",
  ],
  "knx-entities-view": [
    "_filters",
    "_expandedFilter",
    "_activeGrouping",
    "_activeSorting",
    "_storedColumns",
  ],
  "knx-expose-view": [
    "_filters",
    "_expandedFilter",
    "_activeGrouping",
    "_activeSorting",
    "_storedColumns",
  ],
  "knx-project-view": [
    "rangeSelectorHidden",
    "_visibleGroupAddresses",
    "_viewMode",
    "_devicesShowFilters",
    "_devicesSearchText",
    "_devicesExpandedFilter",
    "_devicesFilterDpt",
    "_devicesFilterLocation",
    "_devicesFilterLine",
    "_storedColumns",
  ],
  "knx-create-entity": [
    "_config",
    "_mode",
    "_yamlErrors",
    "_validationErrors",
    "_validationBaseError",
  ],
  "knx-create-expose": [
    "_entityId",
    "_config",
    "_mode",
    "_showRawValues",
    "_showNotesDialog",
    "_yamlErrors",
    "_validationErrors",
    "_validationBaseError",
  ],
  "knx-dpt-reference": ["_filter"],
  "knx-group-monitor": [
    "_projectAlertDismissed",
    "_storedColumns",
    "controller._filters",
    "controller._sortColumn",
    "controller._sortDirection",
    "controller._expandedFilter",
    "controller._isReloadEnabled",
    "controller._isPaused",
    "controller._timeDeltaBefore",
    "controller._timeDeltaAfter",
    "controller._filterStartMs",
    "controller._filterEndMs",
  ],
  "knx-send-dialog": ["_data"],
  "knx-time-server-dialog": ["_data", "_errors"],
  "knx-dpt-select-dialog": ["_selected", "_filter"],
  "knx-ga-select-dialog": ["_selected", "_filter"],
  "knx-device-create-dialog": ["_deviceName", "_area"],
  "knx-group-monitor-telegram-info-dialog": ["_params.telegram"],
  "knx-project-upload-dialog": ["_projectPassword"],
  // Files remain browser-owned; the local example password is ordinary form state.
  "hass-tabs-subpage-data-table": [
    "filter",
    "showFilters",
    "selected",
    "_sortColumn",
    "_sortDirection",
    "_groupColumn",
    "_selectMode",
    "columnOrder",
    "hiddenColumns",
  ],
  "ha-data-table": [
    "filter",
    "_filter",
    "sortColumn",
    "sortDirection",
    "groupColumn",
    "_collapsedGroups",
    "_checkedRows",
    "_lastSelectedRowId",
    "columnOrder",
    "hiddenColumns",
  ],
  "dialog-data-table-settings": ["_columnOrder", "_hiddenColumns"],
  "ha-dropdown": ["open"],
  "ha-dialog": ["open"],
  "ha-adaptive-dialog": ["open"],
  "ha-adaptive-popover": ["open"],
  "ha-bottom-sheet": ["open"],
  "ha-expansion-panel": ["expanded"],
  "flex-content-expansion-panel": ["expanded"],
  "ha-generic-picker": [
    "value",
    "selectedSection",
    "_opened",
    "_pickerWrapperOpen",
    "_selectedValue",
    "_newValue",
  ],
  "ha-picker-combo-box": [
    "value",
    "selectedSection",
    "_search",
    "_items",
    "_selectedSection",
    "_valuePinned",
    "_selectedItemIndex",
  ],
  "ha-date-range-picker": ["startDate", "endDate", "_opened", "_pickerWrapperOpen"],
  "ha-input": ["value"],
  "ha-input-search": ["value"],
  "ha-textfield": ["value"],
  "ha-textarea": ["value"],
  "ha-select": ["value", "_opened"],
  "ha-checkbox": ["checked", "indeterminate"],
  "ha-switch": ["checked"],
  "ha-radio-group": ["value"],
  "ha-radio-option": ["checked"],
  "ha-slider": ["value"],
  "ha-selector": ["value"],
  "ha-selector-number": ["value"],
  "ha-selector-select": ["value"],
  "ha-selector-boolean": ["value"],
  "ha-selector-text": ["value"],
  "ha-yaml-editor": ["value", "_yaml", "isValid"],
  "ha-code-editor": ["value", "_isFullscreen"],
  input: ["value", "checked", "indeterminate"],
  textarea: ["value"],
  select: ["value", "selectedIndex"],
  details: ["open"],
};

// Catalog controls are the public allowlist. Example-only controls are ignored by
// the synchronizer when the corresponding property does not exist on the element.
const localProperties = new Set([
  "hass",
  "knx",
  "narrow",
  "isWide",
  "isMobileDevice",
  "filterPaneNarrow",
]);
for (const { meta } of catalog) {
  syncBindings[meta.tag] = [
    ...new Set([
      ...(syncBindings[meta.tag] ?? []),
      ...meta.controls.map(({ key }) => key).filter((key) => !localProperties.has(key)),
    ]),
  ];
}

// These UI-only launch methods rebuild parameters and callbacks in the peer realm.
export const dialogOpeners: Record<string, Record<string, string>> = {
  "knx-dpt-dialog-selector": { "knx-dpt-select-dialog": "_openDialog" },
  "knx-single-address-selector": { "knx-ga-select-dialog": "_openDialog" },
  "knx-device-picker": { "knx-device-create-dialog": "_openCreateDeviceDialog" },
  "knx-dashboard": {
    "knx-send-dialog": "_openSendDialog",
    "knx-project-upload-dialog": "_openProjectUploadDialog",
    "knx-time-server-dialog": "_openTimeServerDialog",
  },
  "knx-group-monitor": { "knx-project-upload-dialog": "_openProjectUploadDialog" },
};
